name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Download Code
      run: |
        git clone https://github.com/aria2/aria2.git
        pwd
      
    - name: configure
      run: |
        cd /home/runner/work/action/action/
        ./configure
        
    - name: make
      run: make
      
    - name: make check
      run: make check
      
    - name: make distcheck
      run: make distcheck

    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: aria2c
        path: /home/runner/work/action/action/src/aria2c   
