name: Aria2c

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Download Code
      run: |
        git clone https://github.com/aria2/aria2.git
        pwd
        ls
      
    - name: configure
      run: |
        cd /home/runner/work/action/action/aria2
        autoreconf -i
        ./configure
        make
        
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: aria2c
        path: /home/runner/work/action/action/aria2/src/aria2c   
